GET http://localhost:5500

###
GET http://localhost:5500/user



###
GET http://localhost:5500/product/vimal


###
GET http://localhost:5500/blog/vimal

###
POST http://localhost:5500/auth/register
Content-Type: application/json

{
    "password": "123456",
    "name": "vimal kumar",
    "email": "vv@vv.vv",
    "imgurl": "https://delegatestudio.com/wp-content/uploads/2020/09/Watchual-Watch-Shop-Online-eCommerce-Store-Ready-Made-WooCommerce-Website-Theme-500x550.jpg"
}

###
POST http://localhost:5500/auth/login
Content-Type: application/json

{
    "password": "54454454",
    "email": "vifhvvg@gghh.vom"
}

###
POST http://localhost:5500/blog
Content-Type: application/json

{
    "title": "vimal",
    "url": "vimalverma",
    "body": "Jihjghjghgm",
    "tags": ["vimal","kumar"],
    "category": "vimal",
    "author": "60a883e6306754cd6a6d5717",
    "imgurl": "https://delegatestudio.com/wp-content/uploads/2020/09/Watchual-Watch-Shop-Online-eCommerce-Store-Ready-Made-WooCommerce-Website-Theme-500x550.jpg"
}

###
POST http://localhost:5500/product
Content-Type: application/json

{
    "name": "vimalverma",
    "url": "vimalverma",
    "price": "100",
    "tags": ["vimal","kumar"],
    "features": "amazing",
    "description": "website",
    "imgurl": "https://delegatestudio.com/wp-content/uploads/2020/09/Watchual-Watch-Shop-Online-eCommerce-Store-Ready-Made-WooCommerce-Website-Theme-500x550.jpg"
}